---
driver:
  name: lxd_cli

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    data_bags_path: "test/integration/default/data_bags"
    run_list:
      - recipe[hutchbase-gw::default]
    attributes:
