name 'hutchbase-gw'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures hutchbase-gw'
long_description 'Installs/Configures hutchbase-gw'
version '0.1.0'
