name 'hutchbase-gw'
maintainer 'Scientific Computing'
maintainer_email 'scicomp@fredhutch.org'
license 'apache'
description 'Installs/Configures hutchbase-gw'
long_description 'Installs/Configures hutchbase-gw'
version '0.1.0'
source_url 'https://github.com/FredHutch/hutchbase-gw'
issues_url 'https://github.com/FredHutch/hutchbase-gw/issues'

depends 'nginx', '~> 2.7.9'
depends 'chef-vault'
